export const ADD_PRODUCT_REQUEST="ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAILURE="ADD_PRODUCT_FAILURE"

export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE="GET_PRODUCT_FAILURE"

export const SINGLE_PRODUCT_REQUEST="SINGLE_PRODUCT_REQUEST"
export const SINGLE_PRODUCT_SUCCESS="SINGLE_PRODUCT_SUCCESS"
export const SINGLE_PRODUCT_FAILURE="SINGLE_PRODUCT_FAILURE"

export const UPDATE_PRODUCT_REQUEST="UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAILURE="UPDATE_PRODUCT_FAILURE"

export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILURE="DELETE_PRODUCT_FAILURE"